### ISSUE TITLE
Additional academic icons?

### ISSUE THREAD

**Issue by cboettig** [dtnedry/academicons#1]
Thanks so much for sharing your implementation of these svg icons. Very elegant and much appreciated (particularly as someone who has been watching [FontAwesome#541](https://github.com/FortAwesome/Font-Awesome/issues/541) for a long time ;-)).

Wondering if you would consider implementing similar icons for either of these:

- [Orcid identifiers] (http://orcid.org/trademark-and-id-display-guidelines) ![](http://orcid.org/sites/default/files/files/ID_symbol_B-W_16x16.png)
- [impactstory](https://github.com/FortAwesome/Font-Awesome/issues/4180) ![](http://www.carlboettiger.info/assets/img/impactstory.ico)

**Comment by dtnedry** [comment]
Thanks for the feedback! I've added these icons now.
